### PR TITLE
add statement

### PR DESCRIPTION
**Pull request by HavierD**

### CODE REVIEW

**Review by utas-raymondng — CHANGES_REQUESTED** [review]
Please add test case

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Comment by utas-raymondng** [comment]
@HavierD please update notion page for your new fields 
https://www.notion.so/imos-world/STAC-file-format-36ca2b2e990f4ba0bd5de9832a473a97

**Comment by HavierD** [comment]
> @HavierD please update notion page for your new fields https://www.notion.so/imos-world/STAC-file-format-36ca2b2e990f4ba0bd5de9832a473a97

👍

**Comment by HavierD** [comment]
> @HavierD please update notion page for your new fields https://www.notion.so/imos-world/STAC-file-format-36ca2b2e990f4ba0bd5de9832a473a97

Will do it after a Nat-chat. ticket for reminding myself: https://github.com/aodn/backlog/issues/5757

**Pull request merged**
